quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=https://sandbox.kie.org,http://localhost:8080,http://localhost,https://attractiepark.onrender.com
quarkus.http.cors.methods=GET,POST
kogito.decisions.validation=IGNORE
